# Generated by Django 3.2.15 on 2023-06-19 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederalEntity',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('zone_type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementType',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('zone_type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip_code', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('locality', models.CharField(default='', max_length=255)),
                ('federal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.federalentity')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality')),
                ('settlements', models.ManyToManyField(to='core.Settlement')),
            ],
        ),
    ]
